const puppeteer = require("puppeteer");
const path = require("path");

const generatePDF = async (companyName, reportContent) => {
  try {
    const browser = await puppeteer.launch();

    const page = await browser.newPage();

    const formattedContent = reportContent
      .replace(/\*\*(.*?)\*\*/g, "<h2>$1</h2>")
      .replace(/^# (.*$)/gim, "<h1>$1</h1>")
      .replace(/^## (.*$)/gim, "<h2>$1</h2>")
      .replace(/^### (.*$)/gim, "<h3>$1</h3>")
      .replace(/\n\n/g, "</p><p>")
      .replace(/\n/g, "</p><p>");

    const htmlContent = `
      <html>
        <head>
          <style>
            body {
              font-family: Arial, sans-serif;
              padding: 40px;
              color: #333;
              line-height: 1.8;
              background-color: #ffffff;
            }

            .container {
              max-width: 900px;
              margin: auto;
            }

            .header {
              text-align: center;
              margin-bottom: 50px;
              border-bottom: 2px solid #111;
              padding-bottom: 20px;
            }

            .header h1 {
              color: #111;
              font-size: 34px;
              margin-bottom: 10px;
            }

            .header p {
              color: #666;
              font-size: 14px;
            }

            .report-content {
              margin-top: 30px;
              font-size: 16px;
            }

            .report-content p {
              margin-bottom: 18px;
            }

            .report-content h1,
            .report-content h2,
            .report-content h3 {
              margin-top: 28px;
              margin-bottom: 12px;
              color: #111;
            }

            .report-content h2 {
              border-left: 4px solid #111;
              padding-left: 10px;
              font-size: 22px;
            }

            .report-content br {
              line-height: 1.8;
            }

            ul {
              margin-left: 20px;
            }

            li {
              margin-bottom: 8px;
            }

            .footer {
              margin-top: 60px;
              text-align: center;
              font-size: 12px;
              color: gray;
              border-top: 1px solid #ddd;
              padding-top: 15px;
            }
          </style>
        </head>

        <body>
          <div class="container">

            <div class="header">
              <h1>${companyName} Business Audit Report</h1>
              <p>Generated by AI Lead Automation System</p>
            </div>

            <div class="report-content">
  ${formattedContent}
</div>

            <div class="footer">
              Generated automatically using AI-powered company analysis.
            </div>

          </div>
        </body>
      </html>
    `;

    await page.setContent(htmlContent, {
      waitUntil: "domcontentloaded",
    });

    const filePath = path.join(
      __dirname,
      `../reports/${companyName.replace(/\s/g, "_")}_Report.pdf`
    );

    await page.pdf({
      path: filePath,
      format: "A4",
      printBackground: true,
      margin: {
        top: "20px",
        bottom: "20px",
        left: "20px",
        right: "20px",
      },
    });

    await browser.close();

    return filePath;
  } catch (error) {
    console.log("PDF Error:", error.message);

    return null;
  }
};

module.exports = generatePDF;